# This is a basic workflow to help you get started with Actions

language: c
dist: xenial
compiler: gcc
sudo: required
install:
    - sudo apt-get update
     #Install cmake
    - sudo apt install -y cmake

     #Install valgrind
    - sudo apt-get install -y valgrind

    #Install cppcheck
    - sudo apt-get install -y cppcheck

    - sudo apt-get install python-numpy python-scipy python-matplotlib ipython python-pandas python-sympy python-nose

script:
    - cd ../
    - git clone https://github.com/python/cpython.git
    - cd c_projects_word_finder
    
    - mkdir build
    - cd build
    - find ../../cpython -iname '*.c' > ../tests/filelist.txt
    - cmake ../
    - make buildAll
    - cppcheck ../ -ibuild
    - valgrind --tool=memcheck --leak-check=full --show-leak-kinds=all --leak-resolution=med  --track-origins=yes ./c_projects_word_finder_staticTest 
    - valgrind --tool=memcheck --leak-check=full --show-leak-kinds=all --leak-resolution=med  --track-origins=yes ./c_projects_word_finder_dynamicTest
    - ./c_projects_word_finder_staticBenchmark --benchmark_format=json --benchmark_out=static.json > /dev/null
    - ./c_projects_word_finder_dynamicBenchmark --benchmark_format=json --benchmark_out=dynamic.json > /dev/null
    - benchmark-src/tools/compare.py benchmarks ./static.json ./dynamic.json
    - current_sha=$(git rev-parse HEAD)
    - bash <(curl -s https://codecov.io/bash) -C $current_sha